Repository foodtruckforager/ftf, pull requests merged in 2020-09, with the labels that each got.

#1 (fix) fix for readme formatting, line indentation in env variables se…
  README.md
  show
Labels: documentation

#4 (add) added multiline to owner edit form and profile
  client/components/screens/TruckOwnerProfile.tsx
  client/components/screens/TruckOwnerProfileEdit.tsx
  client/components/screens/TruckOwnerRouter.tsx
Labels: frontend

#24 (fix) fixed info card on posts/reviews, fixed setTimeout in in initial load
  client/components/dropIns/Map.tsx
  client/components/dropIns/header.tsx
  client/components/routes/trackerStack.tsx
  client/components/screens/truckDetails.tsx
  client/components/screens/truckPosts.tsx
  client/components/screens/truckReviews.tsx
Labels: front-end

#27 (fix) cloudinary profile photo uploads fix, added photo upload icon, …
  client/Accordion/Accordion.tsx
  client/components/dropIns/UserProfileSettingsOverlay.tsx
  client/components/screens/settings.tsx
  server/routes/user.js
Labels: back-end, front-end

#28 (fix) changed colors to blue in Accordion chevron
  client/Accordion/Chevron.tsx
Labels: front-end

#29 (add) added imageUploadOverlay with tensorflow for reviews
  client/components/dropIns/ImageUploadOverlay.tsx
  client/components/dropIns/SubmitOverlay.tsx
  client/components/routes/drawer.tsx
  server/db/models/Photo.js
  server/db/models/Review.js
  server/routes/truck.js
  server/routes/user.js
Labels: back-end, front-end

#31 (fix) fixed buttons on review overlay, need to move buttons lower
  client/components/dropIns/ImageUploadOverlay.tsx
  client/components/dropIns/SubmitOverlay.tsx
Labels: front-end

#32 Tensorflow.js cloudinary image upload integration
  client/Accordion/Accordion.tsx
  client/Accordion/Settings.tsx
  client/components/dropIns/ImageUploadOverlay.tsx
  client/components/dropIns/SubmitOverlay.tsx
  client/components/routes/trackerStack.tsx
  client/components/screens/settings.tsx
Labels: front-end

#35 (add) Truck posts machine learning integrated, trucks can add photos with posts
  client/Accordion/Accordion.tsx
  client/components/dropIns/GoogleLogIn.tsx
  client/components/dropIns/ImageUploadOverlay.tsx
  client/components/dropIns/Map.tsx
  client/components/dropIns/SubmitOverlay.tsx
  client/components/dropIns/TruckPostItem.tsx
  client/components/dropIns/TruckReviewItem.tsx
  client/components/dropIns/UserProfileSettingsOverlay.tsx
  client/components/screens/LogIn.tsx
  client/components/screens/ScanQRCode.tsx
  client/components/screens/TruckOwnerProfile.tsx
  client/components/screens/TruckOwnerProfileEdit.tsx
  client/components/screens/TruckOwnerRouter.tsx
  client/components/screens/settings.tsx
  client/components/screens/truckDetails.tsx
  client/components/screens/truckPosts.tsx
  client/components/screens/truckReviews.tsx
  server/db/db.js
  server/db/models/Post.js
  server/routes/truck.js
  server/routes/user.js
  server/test/test.js
Labels: back-end, enhancement, front-end

#40 (in progress) photo forager added routes to get all truck reviews and…
  client/components/routes/drawer.tsx
  client/components/routes/trackerStack.tsx
  client/components/screens/PhotoForager.tsx
  package-lock.json
  package.json
  server/routes/truck.js
  server/routes/user.js
Labels: back-end, front-end

#41 (add) Photo forager keywords rendered
  client/components/screens/PhotoForager.tsx
  package-lock.json
  package.json
  server/routes/truck.js
  server/routes/user.js
Labels: front-end

#42 (add) Machine learning photo overlay
  client/components/routes/trackerStack.tsx
  client/components/screens/PhotoForager.tsx
Labels: front-end

#43 (add) capitalize-food-genre names
  client/Accordion/Accordion.tsx
  client/components/dropIns/ImageUploadOverlay.tsx
  client/components/routes/drawer.tsx
  client/components/screens/ImageUpload.tsx
Labels: front-end
