Repository foodtruckforager/ftf, pull requests merged in 2020-10, with the labels that each got.

#44 (add) times now show how long it has been the item was posted from now
  client/Accordion/Accordion.tsx
  client/components/dropIns/TruckPostItem.tsx
  client/components/dropIns/TruckReviewItem.tsx
  package-lock.json
  package.json
Labels: front-end

#47 (fix) keywords are properly pulled from database on food truck forage…
  client/components/screens/PhotoForager.tsx
  server/test/test.js
Labels: front-end

#48 (add) added truck gif to login screen
  assets/tacoTruck.gif
  client/components/dropIns/GoogleLogIn.tsx
  client/components/dropIns/SubmitOverlay.tsx
  client/components/screens/LogIn.tsx
  client/components/screens/TruckOwnerProfile.tsx
  client/components/screens/TruckOwnerProfileEdit.tsx
Labels: front-end

#54 (fix) removed trailing commas from keywords in reviews and truck posts
  client/components/dropIns/TruckPostItem.tsx
  client/components/dropIns/TruckReviewItem.tsx
  client/components/routes/drawer.tsx
  client/components/routes/trackerStack.tsx
Labels: front-end

#55 (fix) Trucks now properly show updated average star rating, and total…
  client/components/dropIns/ImageUploadOverlay.tsx
  client/components/dropIns/InfoWindow.tsx
  client/components/dropIns/SubmitOverlay.tsx
  client/components/dropIns/TruckPostItem.tsx
  client/components/dropIns/TruckReviewItem.tsx
Labels: front-end

#58 (fix) revamped owner profile, working blurb dropdown
  client/components/screens/TruckOwnerProfile.tsx
  package-lock.json
  package.json
Labels: front-end

#59 (add) added tooltip for badges
  client/Accordion/Badges.tsx
Labels: front-end

#60 (fix) formatted truck details, posts, and reviews, fixed css
  client/components/screens/truckDetails.tsx
  client/components/screens/truckPosts.tsx
  client/components/screens/truckReviews.tsx
Labels: front-end

#62 (add) added light-blue/dark-blue/sea-green color theme
  App.tsx
  babel.config.js
  client/Accordion/Accordion.tsx
  client/Accordion/Badges.tsx
  client/Accordion/Chevron.tsx
  client/Accordion/FavoriteTruck.tsx
  client/Accordion/ListItem.tsx
  client/components/dropIns/GoogleLogIn.tsx
  client/components/dropIns/ImageUploadOverlay.tsx
  client/components/dropIns/InfoWindow.tsx
  client/components/dropIns/Map.tsx
  client/components/dropIns/MapSearch.tsx
  client/components/dropIns/SubmitOverlay.tsx
  client/components/dropIns/TruckReviewItem.tsx
  client/components/dropIns/UserProfileSettingsOverlay.tsx
  client/components/dropIns/header.tsx
  client/components/routes/trackerStack.tsx
  client/components/screens/GenerateQRCode.tsx
  client/components/screens/LogIn.tsx
  client/components/screens/TruckOwnerProfile.tsx
  client/components/screens/TruckOwnerProfileEdit.tsx
  client/components/screens/TruckOwnerRouter.tsx
  client/components/screens/settings.tsx
  client/components/screens/tracker.tsx
  client/components/screens/truckDetails.tsx
  client/components/screens/truckPosts.tsx
  client/components/screens/truckReviews.tsx
  package-lock.json
  package.json
  server/routes/truck.js
Labels: front-end

#63 (fix) formatting-fix-post-color-change
  client/components/dropIns/GoogleLogIn.tsx
  client/components/screens/settings.tsx
  client/components/screens/truckDetails.tsx
  client/components/screens/truckPosts.tsx
  client/components/screens/truckReviews.tsx
Labels: front-end

#64 (fix) made top three truck buttons light blue
  client/components/screens/truckDetails.tsx
  client/components/screens/truckPosts.tsx
  client/components/screens/truckReviews.tsx
Labels: front-end

#65 (fix) fixed css and formatting in reviews, posts, and truck profile
  client/components/dropIns/TruckReviewItem.tsx
  client/components/screens/TruckOwnerProfile.tsx
  client/components/screens/truckPosts.tsx
  client/components/screens/truckReviews.tsx
Labels: front-end

#66 (fix) changed header color to turquoise, made info logo round
  App.tsx
  client/Accordion/Chevron.tsx
  client/components/dropIns/InfoWindow.tsx
  client/components/dropIns/Thumbnail.tsx
  client/components/routes/trackerStack.tsx
  client/components/screens/settings.tsx
Labels: front-end

#67 (add) blurb-removed-from-reviews-posts
  client/components/dropIns/InfoWindow.tsx
  client/components/screens/tracker.tsx
  client/components/screens/truckDetails.tsx
  client/components/screens/truckPosts.tsx
  client/components/screens/truckReviews.tsx
Labels: front-end

#69 (add) added spinner to tracker and changed pressed button color
  App.tsx
  client/components/dropIns/MapSearch.tsx
  client/components/screens/tracker.tsx
  client/components/screens/truckDetails.tsx
  client/components/screens/truckPosts.tsx
  client/components/screens/truckReviews.tsx
Labels: front-end

#70 (fix) revamped truck owner edit page, added spinner to truck owner
  client/components/screens/TruckOwnerProfile.tsx
  client/components/screens/TruckOwnerProfileEdit.tsx
  package-lock.json
  package.json
Labels: front-end

#71 (add) added spinner to user profile, user can change name
  client/Accordion/Accordion.tsx
  client/components/dropIns/UserProfileSettingsOverlay.tsx
  client/components/screens/settings.tsx
Labels: front-end

#72 (fix) keywords-null-post-review-item-fix
  client/components/dropIns/TruckPostItem.tsx
  client/components/dropIns/TruckReviewItem.tsx
  client/components/screens/tracker.tsx
  server/test/test.js
Labels: front-end

#73 (fix) User profile blank fix
  client/Accordion/Accordion.tsx
  client/components/dropIns/MapSearch.tsx
  client/components/dropIns/TruckPostItem.tsx
  client/components/dropIns/TruckReviewItem.tsx
  client/components/dropIns/UserProfileSettingsOverlay.tsx
  client/components/screens/TruckOwnerProfile.tsx
  client/components/screens/TruckOwnerProfileEdit.tsx
  client/components/screens/settings.tsx
  client/components/screens/tracker.tsx
  client/components/screens/truckDetails.tsx
  client/components/screens/truckPosts.tsx
  client/components/screens/truckReviews.tsx
  server/test/test.js
Labels: front-end

#74 (fix) keywords show up again on photo upload
  client/components/dropIns/ImageUploadOverlay.tsx
  client/components/dropIns/TruckPostItem.tsx
  client/components/screens/ScanQRCode.tsx
  server/test/test.js
Labels: front-end

#75 (add) Added spinners back/added revamped owner edit page
  client/Accordion/Accordion.tsx
  client/components/dropIns/MapSearch.tsx
  client/components/dropIns/UserProfileSettingsOverlay.tsx
  client/components/screens/TruckOwnerProfile.tsx
  client/components/screens/TruckOwnerProfileEdit.tsx
  client/components/screens/settings.tsx
  client/components/screens/tracker.tsx
  client/components/screens/truckDetails.tsx
  client/components/screens/truckPosts.tsx
  client/components/screens/truckReviews.tsx
Labels: front-end

#76 (add) search placeholder updated, added username edit for user
  client/components/dropIns/MapSearch.tsx
  client/components/dropIns/UserProfileSettingsOverlay.tsx
Labels: front-end

#77 (fix) feastmode badge now correctly waits for 30 visits before being …
  client/Accordion/Accordion.tsx
Labels: front-end

#78 (fix) removed duplicate entry in test-db
  server/test/test.js
Labels: back-end

#79 (update) Updating readme branch
  App.tsx
  README.md
Labels: documentation

#80 (remove) removed dark theme attempt
  App.tsx
Labels: front-end

#81 (fix) fixed spinner location on tracker page
  client/components/dropIns/MapSearch.tsx
Labels: front-end

#82 (fix) fix upper margin for truck create post, disabled yellow error box
  App.tsx
  client/components/dropIns/SubmitOverlay.tsx
Labels: front-end

#83 (fix)Fixed blank truck creation screen branch
  client/components/dropIns/GoogleLogIn.tsx
  client/components/screens/TruckOwnerRouter.tsx
Labels: front-end
